name = "DOPBrowser"
uuid = "a1b2c3d4-5678-90ab-cdef-1234567890ab"
version = "0.1.0"
authors = ["DOP Browser Contributors"]

[deps]
Blobs = "163b9779-6631-5f90-a265-3de947924de8"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticCompiler = "81625895-6c0f-48fc-b932-11a18313743c"
StaticTools = "86c06d3c-3f03-46de-9781-57580aa96d0a"

[compat]
Blobs = "1.2.0"
Logging = "1.11.0"
PackageCompiler = "2.2.4"
StaticArrays = "1.9"
StaticCompiler = "0.7"
StaticTools = "0.8.12"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
