name = "DOPBrowser"
uuid = "a1b2c3d4-5678-90ab-cdef-1234567890ab"
version = "0.1.0"
authors = ["DOP Browser Contributors"]

[deps]
Blobs = "163b9779-6631-5f90-a265-3de947924de8"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Blobs = "1.2.0"
StaticArrays = "1.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
